name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" > keystore_base64.txt
          base64 -d keystore_base64.txt > app/keystore.jks  # 确保与项目路径一致
        shell: bash

      - name: Build Release APK
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            :app:assembleRelease
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/app/keystore.jks
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_SIGNING_PASSWORD }}
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }}
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
          build-root-directory: .  # 如果是多模块项目可能需要调整

      # 添加文件检查步骤（调试用）
      - name: List build outputs
        run: ls -R app/build/outputs/apk
        shell: bash

      # 修正上传路径
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/**/*.apk  # 使用双星号递归查找
